sudo: false
language: node_js
node_js:
- '4'
- '5'
- '6'
env:
- TSI2_LING7='build'
- TSI2_LING7='test'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
  - master
script:
- echo npm run $TSI2_LING7
- npm run $TSI2_LING7
